@extends('layouts.admin')
@section('title', ($item->exists ? 'Edit' : 'Tambah').' konten')
@section('content')
@php($label = ['products' => 'produk', 'pillars' => 'keunggulan', 'process-steps' => 'tahap proses'][$type])
<a class="text-link" href="{{ route('admin.content.index', [$company, $type]) }}">← {{ $company->short_name }}</a><div class="admin-heading"><div><span class="eyebrow">{{ $company->name }}</span><h1>{{ $item->exists ? 'Edit' : 'Tambah' }} {{ $label }}</h1></div></div><form class="panel form-panel narrow-panel" method="POST" enctype="multipart/form-data" action="{{ $item->exists ? route('admin.content.update', [$company, $type, $item->id]) : route('admin.content.store', [$company, $type]) }}">@csrf @if($item->exists) @method('PUT') @endif
@if($type === 'products')<x-field name="name" label="Nama produk" :value="$item->name" required maxlength="150"/><x-field name="category" label="Kategori" :value="$item->category" required maxlength="100"/>@else<x-field name="title" label="Judul" :value="$item->title" required maxlength="150"/>@endif
<x-field name="description" type="textarea" label="Deskripsi" :value="$item->description" required maxlength="10000"/>
@if($type === 'products')<x-field name="specifications" type="textarea" label="Spesifikasi" :value="$item->specifications" hint="Tulis satu spesifikasi per baris, misalnya Material: Kertas ivory."/><x-field name="image" type="file" label="Foto produk" accept="image/jpeg,image/png,image/webp" hint="JPG, PNG, atau WebP. Maksimal 5 MB."/>@if($item->image_path)<img src="{{ \App\Actions\Cms\MediaManager::url($item->image_path) }}" class="upload-preview" alt="Foto produk"><label class="checkbox-row"><input type="checkbox" name="remove_image" value="1"> Hapus foto saat disimpan</label>@endif @endif
<x-field name="sort_order" type="number" label="Urutan tampil" :value="$item->sort_order ?? 1" required min="0" max="999"/><label class="checkbox-row"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', session()->hasOldInput() ? false : ($item->exists ? $item->is_active : true)))> Aktif — tampil pada profil perusahaan yang dipublikasikan</label><div class="form-actions"><button class="button" type="submit">Simpan {{ $label }} ✓</button><a href="{{ route('admin.content.index', [$company, $type]) }}">Batal</a></div></form>
@endsection