@extends('layouts.admin')
@section('title', $item->exists ? 'Edit item menu' : 'Tambah item menu')
@section('content')
<a class="text-link" href="{{ route('admin.sites.menus.edit', [$site, $menu]) }}">← {{ $site->resolvedName() }} / {{ $menu->name }}</a><div class="admin-heading"><h1>{{ $item->exists ? 'Edit item menu' : 'Tambah item menu' }}</h1></div>
<form class="panel form-panel" method="POST" action="{{ $item->exists ? route('admin.sites.menus.items.update', [$site, $menu, $item]) : route('admin.sites.menus.items.store', [$site, $menu]) }}">@csrf @if($item->exists) @method('PUT') @endif
<x-field name="label" label="Label menu" :value="$item->label" required maxlength="255"/><x-field name="key" label="Key (opsional, unik dalam menu)" :value="$item->key" maxlength="100"/>
<div class="form-grid"><label class="field"><span>Induk</span><select name="parent_id"><option value="">Menu utama</option>@foreach($parents as $parent)<option value="{{ $parent->id }}" @selected(old('parent_id', $item->parent_id) == $parent->id)>{{ $parent->label }} (#{{ $parent->id }})</option>@endforeach</select></label><label class="field"><span>Bentuk tampilan</span><select name="type">@foreach(['link' => 'Link biasa', 'mega_menu' => 'Mega menu'] as $value => $label)<option value="{{ $value }}" @selected(old('type', $item->type) === $value)>{{ $label }}</option>@endforeach</select></label><x-field name="sort_order" label="Urutan dalam induk" type="number" :value="$item->sort_order" min="0" max="999" required/></div>
<label class="field"><span>Jenis target</span><select name="target">@foreach(['page' => 'Halaman situs', 'service' => 'Layanan', 'url' => 'URL eksternal', 'heading' => 'Heading tanpa tautan'] as $value => $label)<option value="{{ $value }}" @selected(old('target', $target) === $value)>{{ $label }}</option>@endforeach</select></label><p>Isi hanya target yang dipilih. Kosongkan target lainnya saat berganti jenis. Struktur menu maksimal tiga tingkat.</p>
<label class="field"><span>Halaman</span><select name="page_id"><option value="">Tanpa halaman</option>@foreach($pages as $page)<option value="{{ $page->id }}" @selected(old('page_id', $item->page_id) == $page->id)>{{ $page->title }} ({{ $page->is_published ? 'Published' : 'Draft' }})</option>@endforeach</select></label>
<x-field name="anchor" label="Anchor halaman (opsional, tanpa #)" :value="$item->anchor" maxlength="100"/>
<details><summary>Anchor tersedia per halaman</summary>@foreach($pages as $page)<p>{{ $page->title }}: {{ $page->sections->pluck('key')->implode(', ') ?: 'Belum ada section' }}</p>@endforeach</details>
<label class="field"><span>Layanan</span><select name="service_id"><option value="">Tanpa layanan</option>@foreach($services as $service)<option value="{{ $service->id }}" @selected(old('service_id', $item->service_id) == $service->id)>{{ $service->name }} ({{ $service->is_active ? 'Aktif' : 'Nonaktif' }})</option>@endforeach</select></label>
<x-field name="url" label="URL eksternal (HTTP/HTTPS)" :value="$item->url" type="url" maxlength="2048"/>
<label class="checkbox-row"><input type="checkbox" name="open_in_new_tab" value="1" @checked(old('open_in_new_tab', session()->hasOldInput() ? false : $item->open_in_new_tab))> Buka tautan di tab baru</label><label class="checkbox-row"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', session()->hasOldInput() ? false : $item->is_active))> Item aktif</label><button class="button">Simpan item</button></form>
@if($item->exists)<section class="panel form-panel"><p>Item memiliki {{ $item->children_count }} submenu. Pindahkan atau hapus submenu sebelum menghapus item ini.</p><form method="POST" action="{{ route('admin.sites.menus.items.destroy', [$site, $menu, $item]) }}" data-confirm="Hapus item menu ini?">@csrf @method('DELETE')<button class="danger-link">Hapus item</button></form></section>@endif
@endsection
