@extends('layouts.public')
@section('content')
<section class="gateway shell" id="businesses"><div class="hero-intro"><div><div class="eyebrow"><span class="red-dash"></span> ONE GROUP. MORE POSSIBILITIES.</div><h1>Enam keahlian.<br>Satu visi <em>ke depan.</em></h1></div><div class="hero-side"><p>Dari kemasan hingga teknologi produksi. <br>Temukan mitra yang tepat untuk <br>langkah berikutnya dalam bisnis Anda.</p><a href="#company-grid" class="text-link">Jelajahi unit bisnis <span>↓</span></a></div></div>
<div class="gateway-label"><span><span class="status-dot"></span> OUR BUSINESS UNITS</span><span>Pilih perusahaan untuk mengenal lebih dekat <span>↘</span></span></div>
<div class="company-grid" id="company-grid">@forelse($companies as $company)<article class="company-card"><button type="button" data-open-dialog="company-{{ $company->id }}" aria-label="Lihat ringkasan {{ $company->name }}"><div class="company-image"><img src="{{ $company->banner_path ? \App\Actions\Cms\MediaManager::url($company->banner_path) : asset('images/'.$company->illustration.'.svg') }}" alt="{{ $company->banner_path ? $company->name : 'Ilustrasi '.$company->sector }}" width="640" height="800" @if(!$loop->first) loading="lazy" @endif><span class="card-number">{{ str_pad($loop->iteration, 2, '0', STR_PAD_LEFT) }} /</span><span class="card-open" aria-hidden="true">↗</span></div><div class="company-card-body"><span class="card-sector">{{ $company->sector }}</span><h2>{{ $company->short_name }}</h2><p>{{ $company->name }}</p><span class="card-link">Kenali kami <span>→</span></span></div></button><noscript><a href="{{ route('company.show', $company->slug) }}">Read More — {{ $company->short_name }}</a></noscript></article>
<dialog id="company-{{ $company->id }}" class="preview-dialog" aria-labelledby="company-title-{{ $company->id }}"><button type="button" class="dialog-close" data-close-dialog aria-label="Tutup ringkasan">×</button><div class="preview-grid"><img class="preview-image" src="{{ $company->banner_path ? \App\Actions\Cms\MediaManager::url($company->banner_path) : asset('images/'.$company->illustration.'.svg') }}" alt="{{ $company->sector }}" loading="lazy"><div class="preview-content"><span class="eyebrow">{{ $company->sector }}</span><h2 id="company-title-{{ $company->id }}">{{ $company->name }}</h2><p>{{ $company->summary }}</p>@if($company->is_demo)<p class="demo-note">Profil demonstrasi — konten menunggu verifikasi perusahaan.</p>@endif<a href="{{ route('company.show', $company->slug) }}" class="button">Read More <span>↗</span></a></div></div></dialog>
@empty<div class="empty-state">Informasi unit bisnis sedang diperbarui. Silakan kembali lagi.</div>@endforelse</div><div class="gateway-bottom"><span>PACKAGING · MATERIALS · MACHINERY · PRINTING</span><span>Keahlian berbeda. Komitmen yang sama.</span></div></section>
<section class="about-section" id="about"><div class="shell about-grid"><div><div class="eyebrow">01 / ABOUT THE GROUP</div><h2>Bertumbuh bersama.<br>Memberi <em>nilai lebih.</em></h2><a class="text-link" href="#businesses">Kenali jaringan kami <span>↗</span></a></div><div><p class="large-copy">Satu ekosistem yang menghubungkan kebutuhan bisnis Anda.</p><p>PT Thamrin Jaya Group menaungi enam unit bisnis dengan bidang keahlian yang saling melengkapi. Dari cetak dan kemasan, material pendukung, hingga teknologi produksi — setiap unit memiliki fokusnya sendiri dalam mendukung kebutuhan mitra.</p><div class="about-facts"><div><strong>06<span> /</span></strong><span>Unit bisnis terintegrasi</span></div><div><strong>01<span> /</span></strong><span>Semangat kolaborasi</span></div></div></div></div></section>
<section class="shell contact-section" id="contact"><div><div class="eyebrow">LET’S BUILD SOMETHING TOGETHER</div><h2>Apa langkah<br><em>Anda berikutnya?</em></h2><p>Ceritakan kebutuhan Anda kepada unit bisnis yang tepat.<br>Kami siap memulai percakapan.</p></div><div class="contact-units">@foreach($companies as $company)<a href="{{ route('company.show', $company->slug) }}#contact"><span><strong>{{ $company->short_name }}</strong><small>{{ $company->sector }}</small></span><span>↗</span></a>@endforeach</div></section>
@endsection